baseURL = "https://hirosawa-sensei.com/"
languageCode = "en-au"
title = "Hideo Hirosawa Sensei"

[taxonomies]

[params]
  description = "A website devoted to Hideo Hirosawa Sensei, 7th Dan Shihan, the last uchideshi of Morihei Ueshiba (O-Sensei), the Founder of Aikido."
  subhead = "7th Dan, Shihan"
